export const POST_UPLOAD_REQUEST = 'POST_UPLOAD_REQUEST'
export const POST_UPLOAD_SUCCESS = 'POST_UPLOAD_SUCCESS'
export const POST_UPLOAD_FAIL = 'POST_UPLOAD_FAIL'
export const POST_UPLOAD_RESET = 'POST_UPLOAD_RESET'
