export const POST_UPLOAD_REQUEST = 'POST_UPLOAD_REQUEST'
export const POST_UPLOAD_SUCCESS = 'POST_UPLOAD_SUCCESS'
export const POST_UPLOAD_FAIL = 'POST_UPLOAD_FAIL'
export const POST_UPLOAD_RESET = 'POST_UPLOAD_RESET'

export const POST_LIST_REQUEST = 'POST_LIST_REQUEST'
export const POST_LIST_SUCCESS = 'POST_LIST_SUCCESS'
export const POST_LIST_FAIL = 'POST_LIST_FAIL'
export const POST_LIST_RESET = 'POST_LIST_RESET'

export const MY_POST_REQUEST = 'MY_POST_REQUEST'
export const MY_POST_SUCCESS = 'MY_POST_SUCCESS'
export const MY_POST_FAIL = 'MY_POST_FAIL'
export const MY_POST_RESET = 'MY_POST_RESET'

export const POST_UPDATE_LIKES = 'POST_UPDATE_LIKES'
export const POST_ADD_COMMENTS = 'POST_ADD_COMMENTS'
export const POST_DELETE = 'POST_DELETE'
