export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'
export const USER_REGISTER_RESET = 'USER_REGISTER_RESET'

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL'
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET'

export const USER_SEARCH_REQUEST = 'USER_SEARCH_REQUEST'
export const USER_SEARCH_SUCCESS = 'USER_SEARCH_SUCCESS'
export const USER_SEARCH_FAIL = 'USER_SEARCH_FAIL'
export const USER_SEARCH_RESET = 'USER_SEARCH_RESET'

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const GET_OTHER_USER_POSTS_REQUEST = 'GET_OTHER_USER_POSTS_REQUEST'
export const GET_OTHER_USER_POSTS_SUCCESS = 'GET_OTHER_USER_POSTS_SUCCESS'
export const GET_OTHER_USER_POSTS_FAIL = 'GET_OTHER_USER_POSTS_FAIL'

export const FOLLOW_REQUEST_SUCESS = 'FOLLOW_REQUEST_SUCCESS'
export const FOLLOW_REQUEST_FAIL = 'FOLLOW_REQUEST_FAIL'
export const FOLLOW_A_USER = 'FOLLOW_A_USER'
export const UNFOLLOW_A_USER = 'UNFOLLOW_A_USER'
export const FOLLOW_RESET = 'FOLLOW_RESET'

export const TOKEN_EXPIRED = 'TOKEN_EXPIRED'
export const TOKEN_EXPIRED_RESET = 'TOKEN_EXPIRED_RESET'
